services:
  frontend:
    container_name: log_internal_biod_sepakat_frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SECRET_KEY_LOG_INTERNAL: ${NEXT_PUBLIC_SECRET_KEY_LOG_INTERNAL}
    restart: always
    ports:
      - "9004:9004"
    env_file:
      - .env.prod